import './globals.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='content-wrapper'>
        <Providers>
          <header>
            <NavBar />
          </header>
          <main>{children}</main>
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
}
