import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans, Inter } from 'next/font/google';
import { Providers } from './providers';
import NavBar from '@/components/navbar/navbar';

const openSans = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${openSans.className} h-full`}>
      <body className='h-full'>
        <Providers>
          <header className='border-b-1 border-slate-200'>
            <NavBar />
          </header>
          <div className='max-w-7xl mx-auto px-6 grow'>{children}</div>
          <footer className='max-w-7xl mx-auto px-6'>footer</footer>
        </Providers>
      </body>
    </html>
  );
}
