import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { Providers } from './providers'
import NavBar from '@/components/navbar'


const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className=''>
        <Providers>
          <header className='border-b-1 border-slate-200'>
            <NavBar />
          </header>

          {children}
        </Providers>
      </body>
    </html>
  )
}
